### ISSUE TITLE
[please fix] I cant download the pack in the twitch launcher

### ISSUE THREAD

**Issue by G0ld1** [kreezxil/minecolonies-getting-started#24]
I try to download the pack in the twitch launcher and the mod ambient sounds 3 is never download and giving an error downloading file. 

1. Go into the twitch launcher.
2. Download the pack.
3. Let it get to the last mod.
4. Wait a bit and it should appear, at least for me it does.

**Versions:**
 - Minecraft:1.14.4
 - Forge:28.2.3
 - Modpack: Minecolonies Getting Started

**Comment by kreezxil** [comment]
Try https://gdevs.io home of the GD Launcher which doesn't have this problem, it's only requirement is that you have a 64bit java installed. you can get one from https://adoptopenjdk.net when you are there ignore the options, it will have preselected the best one, just hit the blue download button.

But just in case the options that should be selected are to be:
![image](https://user-images.githubusercontent.com/3880072/77100094-0f18d600-69e3-11ea-8e84-e16a3f7220b2.png)

you'll know you don't have 64bit java with hotspot because if you double click a pack in GDL nothing  happens.

I know you asked for Twitch help, Twitch is garbage tbf and tbh. GDL is alpha which is why I'm telling you how to get around any shortcomings you might encounter.

https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions

Back to twitch, i just tried with Twitch and it timed out on a different pack for me. The problem is entirely twitch it has nothing to do with my pack.

Also you'll be much happier with GDL.
